// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Ride.Module.Persistence;

#nullable disable

namespace Ride.Module.Persistence.Migrations
{
    [DbContext(typeof(RideDbContext))]
    [Migration("20260730103818_AddRideUserIdActiveUniqueIndex")]
    partial class AddRideUserIdActiveUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ride.Module.Entities.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Point>("DropoffLocation")
                        .HasColumnType("geography");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("LastLocation")
                        .HasColumnType("geography");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Point>("PickupLocation")
                        .HasColumnType("geography");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Rides_UserId_Active_Unique")
                        .HasFilter("[Status] IN (0, 1, 2)");

                    b.HasIndex("DriverId", "Status", "RequestedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Rides_DriverId_Status_RequestedAt");

                    b.HasIndex("Status", "UserId", "DriverId")
                        .HasDatabaseName("IX_Rides_Status_UserId_DriverId");

                    b.HasIndex("UserId", "Status", "RequestedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Rides_UserId_Status_RequestedAt");

                    b.ToTable("Rides", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
